In [29]:
import utils # descarga automaticamente los archivos al importarlo
import pandas as pd
from icecream import ic
ic.disable()
# se puede cambiar la funcion `display(var)` por `ic(var)`

In [47]:
# E1

data_path = 'ObesityDataSet_raw_and_data_sinthetic.csv'

# a.ii
# utils.mostrar_archivo('ObesityDataSet_raw_and_data_sinthetic.txt')
# utils.mostrar_archivo('ObesityDataSet_raw_and_data_sinthetic.csv')

# a.iii
df = pd.read_csv(data_path)

# a.iv
# display(df.columns.tolist())

# a.v
# display(df.head())
# display(df[0:5])

# a.vi
# display(df.describe())
display(df.describe(include='all')) # esto es para que muestre toda columna, esto va a incluir tambien las cualitativas.

item_b_analizar_columnas = ''' Tipos de datos y que representan
 Age: Cuantitativa discreta - edad
 Gender: Cualitativa nominal - genero: h,m
 Height: Cuantitativa continua - altura en metros
 Weight: Cuantitativa continua - peso en kg
 CALC: Cualitativa ordinal - onsume alcohol: no, a veces, frecuentemente, siempre
 FAVC: BINARIA - Consumo frecuente de comidas altamente caloricas: si, no
 FCVC: Cualitativa ordinal - frecuencia de consumo de vegetales: nunca, a veces, siempre
 NCP: Cualitativa ordinal
 SCC: BINARIA
 SMOKE: BINARIA
 CH2O: Cualitativa ordinal
 family_history_with_overweight: BINARIA
 FAF: Cualitativa ordinal
 TUE: Cualitativa ordinal
 CAEC: Cualitativa ordinal
 MTRANS: Cualitativa nominal (se puede justificar como ordinal)
 NObeyesdad: Cualitativa ordinal
 Falta indice de masa corporal, BMI
'''

Obesidad

La obesidad, que causa problemas físicos y mentales, es un problema de salud global con graves consecuencias. La prevalencia de la obesidad aumenta constantemente, por lo que se necesita nueva investigación que examine los factores que influyen en la obesidad y cómo predecir la aparición de la condición según estos factores.

Los datos fueron recolectados como parte de este trabajo científico: https://www.sciencedirect.com/science/article/pii/S2352340919306985#sec1

Información del Conjunto de Datos

Este conjunto de datos incluye información para la estimación de los niveles de obesidad en individuos de los países de México, Perú y Colombia, en función de sus hábitos alimenticios y condición física. Los datos contienen 17 atributos y 2111 registros, los registros están etiquetados con la variable de clase NObesidad (Nivel de Obesidad), que permite la clasificación de los datos utilizando los valores de Peso Insuficiente, Peso Normal, Sobrepeso Nivel I, Sobrepeso Nivel II, Obesidad Tipo I, Obesidad Tipo II y Obesidad Tipo III. El 77% de los datos se generó sintéticamente utilizando la herramienta Weka y el filtro SMOTE, el 23% de los datos se recolectaron directamente de los usuarios a través de una plataforma web.

Las columnas corresponden a:

Age: age

Height: height

Weight: weight

family_history_with_overweight: Has a family member suffered or suffers f from overweight? - yes or no

FAVC: Frequent consumption of high caloric food - yes or no

FCVC: Frequency of consumption of vegetables - Never, Sometimes, Always

NCP: Number of main meals - 1, 2, 3, 4

CAEC: Consumption of food between meals - No, Sometimes, Frequently, Always

SMOKE: Do you smoke - yes o no

CH2O: Consumption of water daily - Less than a litter, between 1 and 2 l, more than 2 l

SCC: Calories consumption monitoring - yes or no

FAF: Physical activity frequency - 0, 1 to 2, 2 to 4, 4 to 5

TUE: Time using technology devices - 0 to 2, 3 to 5, >5

CALC: Consumption of alcohol - no, sometimes, frequently, always

MTRANS: Transportation used - automobile, motorbike, bike, public_transportation, walking

NObeyesdad: Type of obesity - insufficient_weight, normal_weight, overweight-level_i, overweight-level_ii, obesity_type_i, obesity_type_ii, obesity_type_iii
BMI: Body mass index

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
count,2111.000000,2111,2111.000000,2111.000000,2111,2111,2111.000000,2111.000000,2111,2111,2111.000000,2111,2111.000000,2111.000000,2111,2111,2111
unique,NaN,2,NaN,NaN,4,2,NaN,NaN,2,2,NaN,2,NaN,NaN,4,5,7
top,NaN,Male,NaN,NaN,Sometimes,yes,NaN,NaN,no,no,NaN,yes,NaN,NaN,Sometimes,Public_Transportation,Obesity_Type_I
freq,NaN,1068,NaN,NaN,1401,1866,NaN,NaN,2015,2067,NaN,1726,NaN,NaN,1765,1580,351
mean,24.312600,NaN,1.701677,86.586058,NaN,NaN,2.419043,2.685628,NaN,NaN,2.008011,NaN,1.010298,0.657866,NaN,NaN,NaN
std,6.345968,NaN,0.093305,26.191172,NaN,NaN,0.533927,0.778039,NaN,NaN,0.612953,NaN,0.850592,0.608927,NaN,NaN,NaN
min,14.000000,NaN,1.450000,39.000000,NaN,NaN,1.000000,1.000000,NaN,NaN,1.000000,NaN,0.000000,0.000000,NaN,NaN,NaN
25%,19.947192,NaN,1.630000,65.473343,NaN,NaN,2.000000,2.658738,NaN,NaN,1.584812,NaN,0.124505,0.000000,NaN,NaN,NaN
50%,22.777890,NaN,1.700499,83.000000,NaN,NaN,2.385502,3.000000,NaN,NaN,2.000000,NaN,1.000000,0.625350,NaN,NaN,NaN
75%,26.000000,NaN,1.768464,107.430682,NaN,NaN,3.000000,3.000000,NaN,NaN,2.477420,NaN,1.666678,1.000000,NaN,NaN,NaN
max,61.000000,NaN,1.980000,173.000000,NaN,NaN,3.000000,4.000000,NaN,NaN,3.000000,NaN,3.000000,2.000000,NaN,NaN,NaN